# Schema for the Field Default Token third party settings
field.field.third_party.field_default_token:
  type: mapping
  mapping:
    label_token:
      label: 'Whether or not the specified token contains the value label instead of the key for list fields.'
      type: boolean
